# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
