# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20170712_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories'),
        ),
    ]
