# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_user_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
