# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_challenge_code100_course_standalone'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='sort',
            field=models.CharField(default='courses', max_length=30),
        ),
    ]
